;; Readable Graph Description: ABNF Grammar
;;
;; Below, you will find the grammar of the RGD syntax.
;; This file and grammar were heavily inspired by TOML and its ABNF grammar.
;; The grammar may not be comprehensive or self-evident, so please refer to the
;; prose semantics for additional clarity. This is especially true for
;; understanding how to translate the parsed output to a graph.
;;
;; Some pieces are directly lifted (or slightly modified) from the TOML spec:
;;  - the pure-val types
;;  - comment and new-line semantics
;;  - key value structure
;;
;; You can try the grammar for yourself at the excellent instaparse tool:
;;      http://instaparse.mojombo.com/


;; Document Structure

rgd = empty-doc / headerless-doc / 1*(graph-doc)

empty-doc = *(comment-line / blank-line)

graph-doc = graph-doc-header newline
            *(graph-line)
            node-doc-header newline
            node-doc-body

headerless-doc = [node-doc-header newline]
                 node-doc-body

node-doc-body = node-expression newline *(node-line)
                [edge-doc-body / unterminated-node-line]
                / unterminated-node-line

edge-doc-body = (edge-doc-header / legacy-edge-doc-header) newline
                *(edge-line)
                [unterminated-edge-line]

;; Lines

unterminated-node-line = node-expression / ws comment / rws
unterminated-edge-line = edge-expression / ws comment / rws

graph-line = graph-expression newline / comment-line / blank-line
node-line  = node-expression newline  / comment-line / blank-line
edge-line  = edge-expression newline  / comment-line / blank-line

graph-doc-header = ws section-marker ws %x67.72.61.70.68 ws ; # graph
node-doc-header  = ws section-marker ws %x6e.6f.64.65.73 ws ; # nodes
edge-doc-header  = ws section-marker ws %x65.64.67.65.73 ws ; # edges
legacy-edge-doc-header = section-marker ws

section-marker = %x23  ; #

;; Expression

graph-expression = ws keyval ws

node-expression = ws node ws
node-expression =/ ws node-set ws
node-expression =/ ws legacy-node ws

edge-expression = ws edge ws
edge-expression =/ ws hyper-edge ws
edge-expression =/ ws legacy-edge ws

;; Node

node = key [description]
node-set = key-set [description]
legacy-node = key legacy-description

;; Edge

edge = endpoint rws edgedir rws endpoint [description]
hyper-edge = key-set [description]
legacy-edge = key rws key [legacy-description]
endpoint = key / key-set

edgedir = left-right-dir / right-left-dir / bi-dir / un-dir
left-right-dir = %x2D.3E  ; ->
right-left-dir = %x3C.2D  ; <-
bi-dir = %x3C.3E          ; <>
un-dir = %x2D.2D		  ; --

description = desc-start val
desc-start  = ws %x3A ws ; :

legacy-description = 1*(rws legacy-token)
legacy-token = string / array / date-time / 1*key-rest

;; Whitespace

rws = 1*wschar
ws = *wschar
wschar =  %x20  ; Space
wschar =/ %x09  ; Horizontal tab
blank-line = ws newline

;; Newline

newline =  %x0A     ; LF
newline =/ %x0D.0A  ; CRLF

;; Comment

comment-start-symbol = %x2F.2F ; //
non-ascii = %x80-D7FF / %xE000-10FFFF
non-eol = %x09 / %x20-7F / non-ascii

comment = comment-start-symbol *non-eol
comment-line = ws comment newline

;; Key-Value pairs

keyval = key keyval-sep pure-val

key = quoted-key / unquoted-key
unquoted-key = key-start *key-rest
key-start = ALPHA / DIGIT / %x5F 
key-rest  = ALPHA / DIGIT / %x2D / %x5F / %x2E 
quoted-key = basic-string / literal-string
keyval-sep = ws %x3D ws ; =

pure-val = string / boolean / array / date-time / float / integer
val = metadata / pure-val

;; Key Sets

key-set = set-open key-list set-close

key-list = key-list-item *(array-sep key-list-item)
key-list-item = ws key ws

metadata = keyval *(metadata-sep keyval)
metadata-sep = ws %x2C ws ; ,

set-open = %x7B  ; {
set-close = %x7D ; }

;; String

string = basic-string / literal-string

;; Basic String

basic-string = quotation-mark *basic-char quotation-mark

quotation-mark = %x22            ; "

basic-char = basic-unescaped / escaped
basic-unescaped = wschar / %x21 / %x23-5B / %x5D-7E / non-ascii
escaped = escape escape-seq-char

escape = %x5C                   ; \
escape-seq-char =  %x22         ; "    quotation mark  U+0022
escape-seq-char =/ %x5C         ; \    reverse solidus U+005C
escape-seq-char =/ %x62         ; b    backspace       U+0008
escape-seq-char =/ %x65         ; e    escape          U+001B
escape-seq-char =/ %x66         ; f    form feed       U+000C
escape-seq-char =/ %x6E         ; n    line feed       U+000A
escape-seq-char =/ %x72         ; r    carriage return U+000D
escape-seq-char =/ %x74         ; t    tab             U+0009
escape-seq-char =/ %x75 4HEXDIG ; uXXXX                U+XXXX
escape-seq-char =/ %x78 2HEXDIG ; xHH                  U+00HH
escape-seq-char =/ %x55 8HEXDIG ; UXXXXXXXX            U+XXXXXXXX

;; Literal String

literal-string = apostrophe *literal-char apostrophe

apostrophe = %x27 ; ' apostrophe

literal-char = %x09 / %x20-26 / %x28-7E / non-ascii

;; Integer

integer = dec-int / hex-int / oct-int / bin-int

minus = %x2D                       ; -
plus = %x2B                        ; +
underscore = %x5F                  ; _
digit1-9 = %x31-39                 ; 1-9
digit0-7 = %x30-37                 ; 0-7
digit0-1 = %x30-31                 ; 0-1

hex-prefix = %x30.78               ; 0x
oct-prefix = %x30.6F               ; 0o
bin-prefix = %x30.62               ; 0b

dec-int = [ minus / plus ] unsigned-dec-int
unsigned-dec-int = DIGIT / digit1-9 1*( DIGIT / underscore DIGIT )

hex-int = hex-prefix HEXDIG *( HEXDIG / underscore HEXDIG )
oct-int = oct-prefix digit0-7 *( digit0-7 / underscore digit0-7 )
bin-int = bin-prefix digit0-1 *( digit0-1 / underscore digit0-1 )

;; Float

float = float-int-part ( exp / frac [ exp ] )
float =/ special-float

float-int-part = dec-int
frac = decimal-point zero-prefixable-int
decimal-point = %x2E               ; .
zero-prefixable-int = DIGIT *( DIGIT / underscore DIGIT )

exp = "e" float-exp-part
float-exp-part = [ minus / plus ] zero-prefixable-int

special-float = [ minus / plus ] ( inf / nan )
inf = %x69.6e.66  ; inf
nan = %x6e.61.6e  ; nan

;; Boolean

boolean = true / false

true    = %x74.72.75.65     ; true
false   = %x66.61.6C.73.65  ; false

;; Date and Time (as defined in RFC 3339)

date-time      = offset-date-time / local-date-time / local-date / local-time

date-fullyear  = 4DIGIT
date-month     = 2DIGIT  ; 01-12
date-mday      = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on month/year
time-delim     = "T" / %x20 ; T, t, or space
time-hour      = 2DIGIT  ; 00-23
time-minute    = 2DIGIT  ; 00-59
time-second    = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second rules
time-secfrac   = "." 1*DIGIT
time-numoffset = ( "+" / "-" ) time-hour ":" time-minute
time-offset    = "Z" / time-numoffset

partial-time   = time-hour ":" time-minute [ ":" time-second [ time-secfrac ] ]
full-date      = date-fullyear "-" date-month "-" date-mday
full-time      = partial-time time-offset

;; Offset Date-Time

offset-date-time = full-date time-delim full-time

;; Local Date-Time

local-date-time = full-date time-delim partial-time

;; Local Date

local-date = full-date

;; Local Time

local-time = partial-time

;; Array

array = array-open ws (array-values / ws) ws array-close

array-open =  %x5B ; [
array-close = %x5D ; ]

array-values = pure-val *(ws array-sep ws pure-val) [ws array-sep]
array-item = ws pure-val ws

array-sep = %x2C ; ,

;; Built-in ABNF terms, reproduced here for clarity

ALPHA = %x41-5A / %x61-7A ; A-Z / a-z
DIGIT = %x30-39 ; 0-9
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

